import { getDb } from "./server/db";
import { driveFiles, InsertDriveFile } from "./drizzle/schema";

async function run() {
  const db = await getDb();
  if (!db) {
    console.error("No database connection");
    process.exit(1);
  }

  const seedFiles: InsertDriveFile[] = [
    {
      id: "file-01",
      moduleId: "stage-damos",
      name: "VW_Golf_7_2.0TDI_EDC17C74_Stage1_PopBang.bin",
      category: "Stage 1 Remap",
      extension: "BIN",
      sizeBytes: 2097152,
      driveId: "1A2B3C4D_GOLF7_EDC17",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-stage-damos",
      downloadUrl: "#",
      brand: "Volkswagen",
      ecuType: "Bosch EDC17C74",
      softwareName: "WinOLS 4.51",
      version: "v1.4",
      description: "Archivo Stage 1 probado en banco +184HP/+400Nm con DPF/EGR safe.",
      tags: "vw, golf, tdi, edc17, stage1",
      isVerified: true,
    },
    {
      id: "file-02",
      moduleId: "stage-damos",
      name: "BMW_F30_320d_EDC17C50_DAMOS_FullMappack.a2l",
      category: "DAMOS & A2L",
      extension: "A2L",
      sizeBytes: 4194304,
      driveId: "1B3C4D5E_BMW_F30_A2L",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-stage-damos",
      downloadUrl: "#",
      brand: "BMW",
      ecuType: "Bosch EDC17C50",
      softwareName: "WinOLS",
      version: "v2.0",
      description: "Definición completa con mapas de inyección, rail y presión turbo.",
      tags: "bmw, f30, damos, a2l, mappack",
      isVerified: true,
    },
    {
      id: "file-03",
      moduleId: "stage-damos",
      name: "Audi_S3_8V_2.0TFSI_SIMOS18.1_Original_VR.bin",
      category: "Archivo Original",
      extension: "BIN",
      sizeBytes: 4194304,
      driveId: "1C4D5E6F_AUDI_S3_SIMOS18",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-stage-damos",
      downloadUrl: "#",
      brand: "Audi",
      ecuType: "Continental SIMOS 18.1",
      softwareName: "PCMFlash / KESS3",
      version: "OEM",
      description: "Lectura virtual verificada 100% original stock.",
      tags: "audi, simos18, original, tfsi",
      isVerified: true,
    },
    {
      id: "file-04",
      moduleId: "curso-winols",
      name: "Clase_01_Introduccion_WinOLS_Mapas_3D.mp4",
      category: "Video Formación",
      extension: "MP4",
      sizeBytes: 420000000,
      driveId: "DRIVE_WINOLS_C01",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-curso-winols",
      downloadUrl: "#",
      brand: "Universal",
      ecuType: "Metodología General",
      softwareName: "WinOLS",
      version: "HD 1080p",
      description: "Estructura del mapa, ejes de RPM, carga, interpolación y visualización.",
      tags: "curso, video, clase 1, basico",
      isVerified: true,
    },
    {
      id: "file-05",
      moduleId: "curso-winols",
      name: "Guia_Ejes_Checksum_Calculo_Seguro.pdf",
      category: "Documentación Técnica",
      extension: "PDF",
      sizeBytes: 8500000,
      driveId: "DRIVE_WINOLS_DOCS",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-curso-winols",
      downloadUrl: "#",
      brand: "Universal",
      ecuType: "Checksum",
      softwareName: "WinOLS Manual",
      version: "2026",
      description: "Procedimiento para corregir checksums antes de flashear.",
      tags: "manual, pdf, checksum, winols",
      isVerified: true,
    },
    {
      id: "file-06",
      moduleId: "winols-software",
      name: "WinOLS_Setup_v4.51_Full_Library.zip",
      category: "Instalador",
      extension: "ZIP",
      sizeBytes: 154000000,
      driveId: "DRIVE_WINOLS_SETUP",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-winols-setup",
      downloadUrl: "#",
      brand: "EVC",
      ecuType: "Universal",
      softwareName: "WinOLS",
      version: "4.51",
      description: "Paquete base con librerías y documentación de instalación.",
      tags: "winols, setup, evc, instalador",
      isVerified: true,
    },
    {
      id: "file-07",
      moduleId: "ecm-titanium",
      name: "ECM_Titanium_Drivers_Database_26000.zip",
      category: "Base de Drivers",
      extension: "ZIP",
      sizeBytes: 980000000,
      driveId: "DRIVE_ECM_DRIVERS",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-ecm-titanium",
      downloadUrl: "#",
      brand: "Alientech",
      ecuType: "Multi-marca",
      softwareName: "ECM Titanium",
      version: "26k Drivers",
      description: "Paquete de drivers listos para identificar tablas rápidamente.",
      tags: "ecm, alientech, drivers, titanium",
      isVerified: true,
    },
    {
      id: "file-08",
      moduleId: "software-remap",
      name: "Remap_Toolbox_Suite_2026_Utilities.rar",
      category: "Herramientas Taller",
      extension: "RAR",
      sizeBytes: 650000000,
      driveId: "DRIVE_REMAP_SUITE",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-remap-pack",
      downloadUrl: "#",
      brand: "Universal",
      ecuType: "Multi-marca",
      softwareName: "Toolbox Suite",
      version: "2026.1",
      description: "Generadores de scripts, calculadoras de DTC y utilidades automotrices.",
      tags: "remap, suite, dtc, utilidades",
      isVerified: true,
    },
    {
      id: "file-09",
      moduleId: "key-immo-airbag",
      name: "ImmoOff_AirbagReset_170_Softwares_Collection.iso",
      category: "Reparación Módulos",
      extension: "ISO",
      sizeBytes: 3200000000,
      driveId: "DRIVE_IMMO_AIRBAG_ISO",
      driveWebLink: "https://drive.google.com/drive/folders/tunebank-immo-airbag",
      downloadUrl: "#",
      brand: "Multi-marca",
      ecuType: "BSI / UCH / Airbag",
      softwareName: "170+ Suite",
      version: "Full Pack",
      description: "Colección para anulación de inmovilizador, reset de crash airbag y ajuste de cuadros.",
      tags: "immo off, airbag, km, key code, 170 software",
      isVerified: true,
    },
  ];

  await db.insert(driveFiles).values(seedFiles);
  console.log("Successfully seeded", seedFiles.length, "files!");
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
